[auth]
redirect_uri = "https://agrivijay-dashboard-momonikaa.streamlit.app/oauth2callback"
cookie_secret = "REPLACE_WITH_A_RANDOM_LONG_SECRET_STRING"

[auth.google]
client_id = "YOUR_GOOGLE_CLIENT_ID"
client_secret = "YOUR_GOOGLE_CLIENT_SECRET"
server_metadata_url = "https://accounts.google.com/.well-known/openid-configuration"
