[auth]
redirect_uri = "https://dashboard0agrivijay.streamlit.app/oauth2callback"
cookie_secret = "YOUR_RANDOM_SECRET"
client_id = "153453244677-ts43qiiasqr3nc10p4e9gto6u47f1qoa.apps.googleusercontent.com"
client_secret = "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"
server_metadata_url = "https://accounts.google.com/.well-known/openid-configuration"
